### ISSUE TITLE
Can You be more specific with the files required for analysis?

### ISSUE THREAD

**Issue by smaguireie** [carinelegrand/RiboVIEW#3]
Hi Carine, 

I'm really interested in using RiboVIEW, however I have a few questions regarding the correct fasta/gtf files to use as input (Human). 

In the paper you say "Fasta-format mRNA and ncRNA reference, as well as GTF-format annotation, were downloaded from Ensembl FTP-download page https://www.ensembl.org/info/data/ftp/index.html." 
Can you be more specific regarding what file you're calling the mRNA file - CDS or cDNA? 

Another issue I have is that the transcript names in the gtf file found here don't actually correspond to the names in either of those fasta files (the fasta files have names formatted like ENST00000415118.1 where as the gtf file contains them named without the final .1, eg ENST00000415118) so trying to match them up later wouldn't work without editing one or the other. 

I tried to get around this by using the resources provided by gencode (https://www.gencodegenes.org/human/, the names match), however, again there are issues eg
Using the python script to convert the gtf file to a cds file also fails if I don't remove everything apart from protein coding genes. Also, when attempting to analyse using riboview I end up with 0 transcripts having the correct annotation of start and stop codons. 

I also want to confirm if I need to remove any extra information from the name line for each transcript in the fasta file so that it will match, e.g >ENST00000671466.1 cds chromosome:GRCh38:13:32315086:32316527:1 gene:ENSG00000139618.16 gene_biotype:protein_coding transcript_biotype:protein_coding gene_symbol:BRCA2 description:BRCA2 DNA repair associated [Source:HGNC Symbol;Acc:HGNC:1101] 
to
\>ENST00000671466.1?

Any advice you have on this would be wonderful.

Thank you for taking the time to read this,

Sarah

**Comment by carinelegrand** [comment]
Hello Sarah,

sure, I'll try and answer all of your questions in the following :

- first of all, there is a new version of RiboVIEW, which solves some of the points you mention (GTF converter, mach between FASTA and GTF), available at zenodo : https://zenodo.org/record/4401399

- the mRNA file should be the cDNA file, since RiboVIEW needs to have the 5' and 3' UTRs, in case there are some.

- names match between gtf and fasta : the best option is to get FASTA, bam and GTF files with the exact same mRNA ID. If it's not the case, you can use the option "versionStrip = TRUE" in the functions 'periodicity' and 'enrichmentNoccupancy'. This option had one remaining caveat in version 1 of RiboVIEW, which is fixed in version 2.

- the gtf file converter is only given as a convenience, since this script is not robust to all situations. However, you will find a better, and more robust version of this script, in RiboVIEW 2.0. There are also verbose options which help you detect what exactly is going wrong. You can get back to me if the script of version 2 is still not working. In this case, make sure to use the verbose messages so I can get to understand where your problem lies.

- It's fine if there is further information in the name line in the fasta, because only the first word up to a blank space (in the example you give, only the ID : "ENST00000671466.1") will be used, not considering the rest. So you can leave the name lines as they are.

I hope this helps, and best regards,

Carine

**Comment by carinelegrand** [comment]
Hello Sarah, 

I hope everything is working fine for you now ? 

If I don't receive an answer, I will close the issue at some point.

Regards,
C

**Comment by smaguireie** [comment]
Hi Carine,

Sorry for the delay in replying,

Thank you for the link to Riboview2.0, I have installed and have it working with the test data.

I can use the gif converter on a full GTF file with no errors now.

Unfortunately I am still encountering issues, namely the files Sample*OL.txt have Zero values (Error C.1 in your new Intro_RiboVIEW.pdf) which you suggest to be most likely some problem with the harmony between the CDS, fasta and bam file.

I have gone so far as to make a new fasta and CDS file with exactly the same mRNA IDs and to test using some of the same samples you used in the paper and I still have this issue.

I understand that the issues may be in the GTF and fasta files which you have no control over - however would it be possible to provide the versions of those (human) you’ve used to test perhaps I could at least conclude something has gone wrong further up? (I have followed your supplementary method and definitely get reads aligning to the cDNA.)

If not, I’ll keep trying to understand what it is that is going wrong.

Best wishes,

Sarah









Sarah Maguire, PhD | Research Fellow
Patrick G. Johnston Centre for Cancer Research | Queen's University Belfast | Belfast BT9 7AE
+44 28 9097 2803 | s.maguire@qub.ac.uk<mailto:s.maguire@qub.ac.uk>






On 9 Mar 2021, at 15:15, carinelegrand <notifications@github.com<mailto:notifications@github.com>> wrote:

This message is from an external sender. Please take care when responding, clicking links or opening attachments.


Hello Sarah,

I hope everything is working fine for you now ?

If I don't receive an answer, I will close the issue at some point.

Regards,
C

**Comment by carinelegrand** [comment]
Hello Sarah,

This is indeed a step which is often frustrating (the rest then usually flows without problem), but there is a way to check that GTF / CDS annotation file, fasta and bam files work fine together : 

There normally is a message printed by the function 'periodicity', which looks like the following : 
" There are 119284 transcripts, among  which 49908 have a correct annotation of start and stop codons."
->Are all your transcripts correctly detected ? Is a fair proportion of them "correctly annotated" ?
 
If you have a too small number of correct annotations, I'm afraid it is necessary to look at some individual mRNA transcripts and identify where the AUG and the STOP codon are located, and check what is the difference with what is written in the GTF / CDS annotation file.

Very often, the difference comes from a +/- 1 nucleotide in the annotation of either the AUG location or the STOP location, and there are options in the gtf2table function, which allow to adjust some of these aspects.

I can help you on that by giving you a detailed example of an mRNA transcript and how it should look like in the CDS annotation table.

Kind regards,
Carine

PS : the human dataset I have was constructed a couple of years ago, so it wouldn't be a good practice to use it without trying to update using the latest official data. Especially as the problem possibly lies elsewhere. Let's try some other options before doing anything of the sort.

**Comment by smaguireie** [comment]
Hi Carine,

Thank you for your response,


There normally is a message printed by the function 'periodicity', which looks like the following :
" There are 119284 transcripts, among which 49908 have a correct annotation of start and stop codons."
->Are all your transcripts correctly detected ? Is a fair proportion of them "correctly annotated” ?

The output is  "There are 104266 transcripts, among which 72745 have a correct annotation of start and stop codons” 104266 is the number in the CDS file, so ~ 69% are correctly annotated. This improves to 79358 correctly annoated if I add the flag mitochondrion=T.


I can help you on that by giving you a detailed example of an mRNA transcript and how it should look like in the CDS annotation table.

This would be great - hopefully I will be able to work out what is going on.

Thanks,

Sarah


On 11 Mar 2021, at 15:29, carinelegrand ***@***.******@***.***>> wrote:

This message is from an external sender. Please take care when responding, clicking links or opening attachments.


Hello Sarah,

This is indeed a step which is often frustrating (the rest then usually flows without problem), but there is a way to check that GTF / CDS annotation file, fasta and bam files work fine together :

There normally is a message printed by the function 'periodicity', which looks like the following :
" There are 119284 transcripts, among which 49908 have a correct annotation of start and stop codons."
->Are all your transcripts correctly detected ? Is a fair proportion of them "correctly annotated" ?

If you have a too small number of correct annotations, I'm afraid it is necessary to look at some individual mRNA transcripts and identify where the AUG and the STOP codon are located, and check what is the difference with what is written in the GTF / CDS annotation file.

Very often, the difference comes from a +/- 1 nucleotide in the annotation of either the AUG location or the STOP location, and there are options in the gtf2table function, which allow to adjust some of these aspects.

I can help you on that by giving you a detailed example of an mRNA transcript and how it should look like in the CDS annotation table.

Kind regards,
Carine

PS : the human dataset I have was constructed a couple of years ago, so it wouldn't be a good practice to use it without trying to update using the latest official data. Especially as the problem possibly lies elsewhere. Let's try some other options before doing anything of the sort.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarinelegrand%2FRiboVIEW%2Fissues%2F3%23issuecomment-796819672&data=04%7C01%7Cs.maguire%40qub.ac.uk%7Cb66f376573ea46adb4e808d8e4a271b9%7Ceaab77eab4a549e3a1e8d6dd23a1f286%7C0%7C0%7C637510733634147231%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s5%2BjQRtpP5JuZQpwO%2FUzoJ9soGJ25Zc4%2BmVVTD3HP9o%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARN22FSQGCHGGKZEVO6GA3LTDDOUTANCNFSM4YCYIESQ&data=04%7C01%7Cs.maguire%40qub.ac.uk%7Cb66f376573ea46adb4e808d8e4a271b9%7Ceaab77eab4a549e3a1e8d6dd23a1f286%7C0%7C0%7C637510733634157224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fpKnKHRBUzaI7DQkH5e3PoXb6RHKThEOKUD900uEg9E%3D&reserved=0>.

Sarah Maguire, PhD | Research Fellow
The Patrick G Johnston Centre for Cancer Research
Queen's University Belfast | Belfast BT9 7AE
+44 28 9097 2803 | ***@***.******@***.***>

**Comment by carinelegrand** [comment]
Hello Sarah,

- about the mitochondrial mRNA : it is better not to include them if you are looking at translation by non-mitochondrial ribosome. Otherwise, the analysis would include both and this would introduce a bias in codon enrichment (and codon occupancy).

- please find attached a pdf file which details the annotation in the CDS tabular annotation file and corresponding FASTA entry (and also, if you're curious, GTF file entries and RefSeq equivalent) :
[2021-03-17_example-annotation-CDS-for-RiboVIEW.pdf](https://github.com/carinelegrand/RiboVIEW/files/6157594/2021-03-17_example-annotation-CDS-for-RiboVIEW.pdf)

I hope this helps, feel free to get back to me otherwise,
Carine
